name: epubx
description: Epub Parser for Dart. Epub package fork. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/rbcprolabs/epubx.dart
issue_tracker: https://github.com/rbcprolabs/epubx.dart
version: 4.0.0

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  archive: ^3.1.6
  path: ^1.8.1
  quiver: ^3.2.1
  xml: ^6.4.2
  image: ^4.1.3
  collection: ^1.15.0

dev_dependencies:
  test: ^1.16.7
  pedantic: ^1.11.0
